language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_install:
  npm install -g vsce
install:
  npm install
after_success:
  npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_deploy: ls -al
deploy:
  provider: releases
  api_key: '$GH_TOKEN'
  file: ./extension.vsix
  skip_cleanup: true
  on:
    tags: true